# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a63c56e8fce1daad14faf755c5e2bbcd6e3f01f485163024982f13995e917c8ac6cde338206bf8d70b4134c51e13b25e55f76e926ec471c8a4b77abe9e1af97

test:
  secret_key_base: f09bee3292dee60c6a330584744ccc35acdf87d3c18e725ae2b08c596c7b07aace2a260c0c0592c802299aac021e29bf40cf4920e97895481a2cdb8137c59692

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
